# Project: GESTION-FACTURE
# Makefile created by Dev-C++ 5.11

CPP      = g++.exe -D__DEBUG__
CC       = gcc.exe -D__DEBUG__
WINDRES  = windres.exe
OBJ      = Facture.o Enseignant.o Etudiant.o main.o
LINKOBJ  = Facture.o Enseignant.o Etudiant.o main.o
LIBS     = -L"C:/Users/ELABBASI/Documents/Dev-Cpp/MinGW64/lib" -L"C:/Users/ELABBASI/Documents/Dev-Cpp/MinGW64/x86_64-w64-mingw32/lib" -static-libgcc -g3
INCS     = -I"C:/Users/ELABBASI/Documents/Dev-Cpp/MinGW64/include" -I"C:/Users/ELABBASI/Documents/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"C:/Users/ELABBASI/Documents/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include"
CXXINCS  = -I"C:/Users/ELABBASI/Documents/Dev-Cpp/MinGW64/include" -I"C:/Users/ELABBASI/Documents/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"C:/Users/ELABBASI/Documents/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include" -I"C:/Users/ELABBASI/Documents/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include/c++"
BIN      = GESTION-FACTURE.exe
CXXFLAGS = $(CXXINCS) -g3
CFLAGS   = $(INCS) -g3
RM       = rm.exe -f

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CC) $(LINKOBJ) -o $(BIN) $(LIBS)

Facture.o: Facture.c
	$(CC) -c Facture.c -o Facture.o $(CFLAGS)

Enseignant.o: Enseignant.c
	$(CC) -c Enseignant.c -o Enseignant.o $(CFLAGS)

Etudiant.o: Etudiant.c
	$(CC) -c Etudiant.c -o Etudiant.o $(CFLAGS)

main.o: main.c
	$(CC) -c main.c -o main.o $(CFLAGS)
